# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-17 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='home.Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='votes_given', to='home.User'),
            preserve_default=False,
        ),
    ]
