# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-15 21:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='date_established',
            field=models.DateTimeField(default=datetime.datetime(1995, 1, 3, 0, 0)),
            preserve_default=False,
        ),
    ]
