# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-24 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PartyPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='party',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties_planned', to='party.PartyPerson'),
        ),
    ]
